### ISSUE TITLE
ソースコードの使用について

### ISSUE THREAD

**Issue by akh1r0ck** [nekobean/pytorch_yolov3#2]
突然のご連絡失礼します．
表題の件，ライセンスの記載がなかったのでお聞かせください！
事業で手がけている機械学習プロジェクトで物体認識をすることになっています．
このリポジトリのソースコードをベースとして使いたいのですが，
（入出力関係など微妙に調整させていただくとは思います）
著作権の都合上，念のに使用を許諾していただけますでしょうか？

**Comment by nekobean** [comment]
コメントありがとうございます。
ブログの YOLOv3 の解説記事のために作成したコードですが、使用は自由に使っていただいて構いません。
レポジトリにライセンスファイルがなかったため、一応 MIT ライセンスをつけておきました。

使用方法については [YOLOv3 - 自作データセットで学習する方法について - pystyle](https://pystyle.info/pytorch-yolov3-how-to-train-custom-dataset/) をご参照ください。

**Comment by akh1r0ck** [comment]
ライセンスまで付けていただき恐縮です．（しかもMIT．大助かりです．）
ご対応ありがとうございます！助かります！

ご丁寧に参考文献もご案内していただきありがとうございます．
実はそちらのブログを拝見させていただき，すでに試させていただいています．
クロースしておきますね．
